site_name: SmillingChat
nav:
    - Home: index.md
    - Blog:
        - 20200812:
            - Template test: blog/template.ipynb
        - 20200227:
            - 「Learn Go with Tests」を読んだ: blog/20200207-read_learn_go_with_tests.md
        - 20200113:
            - 最新のニューラル会話モデルでおしゃべりしよう！ - GPT-2でチャットボット作成: blog/gptchat_howto_ja.md
        - 20191223:
            - New GPU Server Setup: blog/20191223-new_gpu_server.md

theme:
    name: material
    palette:
        primary: white
        accent: white
    features:
        - tabs
        - navigation.expand


markdown_extensions:
  - pymdownx.emoji
  - pymdownx.magiclink
  - admonition
  - codehilite:
      linenums: true
      use_pygments: true
plugins:
  # Search must be added when other plugins are loaded
  - search:
      lang: ja
  - mkdocs-jupyter
  
# Add source repository
repo_name: noriyukipy
repo_url: https://github.com/noriyukipy