site_name: ChatBot Talk
nav:
    - Home: index.md
    - Blog: blog.md

theme:
    name: material
    custom_dir: overrides
    favicon: images/favicon.png
    prev_next_buttons_location: none
    palette:
        primary: white
        accent: white
    features:
        # - tabs
        - navigation.expand

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.magiclink
  - admonition
  - codehilite:
      linenums: true
      use_pygments: true
plugins:
  # Search must be added when other plugins are loaded
  - search:
      lang: ja
  - mkdocs-jupyter
  